name: Build index

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: ['main']
    paths:
      - ".github/workflows/build_index.yml"
      - "primerschemes/**"
      - "index.json"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # Runs commands using the runners shell
    - name: Run the build index script
      run: pip install primal-page && primal-page build-index --gitserver ${{github.server_url}} --gitaccount ${{github.repository}} --git-commit-sha ${{github.sha}}
    - name: Commit files  # transfer the new html files back into the repository
      run: |
        git config --local user.name  ${{ github.actor }}        
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Auto updating index"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true